CESNET/Nemea-Framework

- python/unirec/unirec.py
There was a typo in a list comprehension (actually generator) for filtering fields with dynamic length
> Python: wrong size comparison to 1 instead of -1 in unirec class generator

- common/ip_prefix_search/README.md
Per #24, this converts the README into Markdown.
I made a couple of tiny grammar edits, but mostly only focused on formatting, so this doesn't completely close #24 (which is about improving language). Nonetheless, I hope this makes the README easier to read!
> Convert ip_prefix_search README to Markdown

- libtrap/Makefile.am
- libtrap/configure.ac
- libtrap/include/libtrap/trap.h
- libtrap/libtrap.spec.in
- libtrap/m4/ac_define_dir.m4
- libtrap/src/ifc_tcpip.h
- libtrap/src/trap.c
Change fixed location of libtrap sockets to DEFAULTSOCKETDIR, configured by --with-defaultsocketdir=DIR. This closes #27.
The default path was left to /tmp because it causes problems with local build & check.
For RPM packages, the path is set to /var/run/libtrap.
Before creation RPM package at copr, supervisor MUST be fixed to use the correct path (it is accessible by trap_default_socket_path global variable. The format for creating socket names was changed to "trap-%s.sock" that is a little bit shorter, `localhost` did not make sense.
> libtrap sockets

- pytrap/unirecmodule.c
This PR fixes #32.
Tested on Debian 8.6, i686, Python version 2.7.9.
> pytrap: Modification of 32b fields handling

- libtrap/src/ifc_tcpip.c
- libtrap/src/trap.c
- libtrap/src/trap_ifc.h
* absolute time used on sem_timedwait should be properly set now
* new absolute time is computed when blocking is repeated
* removed `int timeout` from trap_set_abs_timespec function
> libtrap: fixed 100% cpu load bug, closes #31

- libtrap/src/trap.c
- libtrap/tests/Makefile.am
- libtrap/tests/test_badparams.c
Added new test, which tries to init context with bad number of IFCs.
Added error message that informs users about IFC numbers.
Fixes #39.
> libtrap: improved error message

- README.md
- pycommon/report2idea.py
**gmtime()**
Convert a time expressed in seconds since the epoch to a struct_time in UTC in which the dst flag is always zero. **If secs is not provided or None, the current time as returned by time() is used.**
> removed unnecessary code

- unirec/unirec.c
- Added check on creation of new record (i.e. record copy destination).
- When creating new record, size of variable length fields is passed instead of whole record size.
> MAINTENANCE: Improved ur_rec_varlen_size() function:

- libtrap/src/ifc_tcpip.c
To avoid cases when a message is dropped, due to interrupt of select(), a patch was created.
There is a check of the remaining time and the original timeout is updated (decreased) after returning from signal callback back to select().
> libtrap: handle signal interrupts to allow alarm() in modules

- libtrap/include/libtrap/trap.h
- libtrap/src/trap.c
- pytrap/pytrapmodule.c
- pytrap/test/pytrapmodule_unittest.py
After printing help or init failure, TrapCtx remained uninitialized.  This leads to segfault during a call of any TrapCtx method.
In libtrap, some assert() macros were replaced by normal checks.
Doc was improved a bit.
> pytrap: BUGFIX segmentation fault on uninitialized context

- libtrap/include/libtrap/trap_module_info.h
it caused malfunctioning of modules and detectors because of change in header file
> module_info: reverting change of type int8_t->int

- pytrap/src/pytrapmodule.c
Definition of VERB_ constants taken from libtrap header file.
> pytrap: improved doc for setVerboseLevel()

- libtrap/configure.ac
- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tls.c
- libtrap/tests/Makefile.am
Added check for return value of tcp socket connection to both interfaces. If it failed, function will end with proper TRAP error code.
Fixed problem with not notifying user that libtrap will be installed without tls interface and then failing on executing tests for tls.
Few minor coding style changes.
> libtrap: return values in tls and tcpip interfaces fixed; closes #82

- libtrap/include/libtrap/trap.h
- libtrap/src/trap.c
- libtrap/tests/basic_test.c
- libtrap/tests/out-buf.c
- libtrap/tests/test_blackhole.c
- libtrap/tests/test_fileifc.c
- libtrap/tests/test_finalize.c
- pytrap/src/pytrapmodule.c
The problem was in the function trap_ctx_init2, where it would destroy the context in every scenario, where TRAP_E_OK did not happen and subsequently returned NULL. However, the calling function trap_init expected NULL only when TRAP_E_MEMORY occurred. This resulted in almost dead code in trap_init function checking other errors. This error in combination with improper setting of error codes in other functions resulted in bad value in error code and error string.
> libtrap: bugfix: "Trap error: No error" solved

- libtrap/src/ifc_tls.c
Closes #91
Removed CHECK_AND_FREE macro that was meant to check against double free errors. However it did not do anything.
> libtrap: removed useless CHECK_AND_FREE macro

- libtrap/src/trap.c
Loaded strings for OpenSSL error messages were not freed.
This patch solves memory leak.
> libtrap: BUGFIX free error strings from OpenSSL

- libtrap/tools/trap_stats.c
It is now possible to use `trap_stats` without `-s` with just PID
or path to socket.
Examples:
```
trap_stats 31270
trap_stats /var/run/libtrap/trap-service_31270.sock
```
The `-s` naturally exists for the backwards compatibility.
> trap_stats: improved input - path to socket

- libtrap/src/ifc_tcpip.c
After a socket was closed because of unsuccessful negotiation,
it was not set to -1. This caused other functions to treat the socket as valid.
Such bahevior resulted in situation where this socket was passed to select() function.
Select() function returns EBADF when a bad file descriptor is passed.
Further fucntions subsequently segfaulted.
> libtrap: bugfix in TCPIP interface

- common/configurator/configurator-internal.h
This pull request fixes an issue that happens during building Nemea-Framework on Raspberry Pi:
_make[5]: Entering directory '/home/pi/projects/nemea/nemea-framework/common'
CXX      configurator/configurator.lo
In file included from configurator/configurator.cpp:59:0:
configurator/configurator-internal.h:92:1: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
};_
> Explicit conversion from int to char

- libtrap/src/trap.c
Creating threads before initializing semaphores the threads wait on is obviously mistake and it results in deadlocks. For instance: if one would use 3 input interfaces and then call trap_ctx_finalize(), the function would call trap_free_ctx_t() which would hang on pthread_join since sem_post would not wake sleeping reader threads since the sem_wait was called when the semaphore was not yet initialized.
I tested the bugfix and it works, the program no longer results in deadlock.
However, I have another issue I would like to address and expect a comment on it.
The whole multi receive thing is kind of  not welcomed in situations when you don't really want to use it, but you have more than one input interface. So currently if you have 10 input interfaces, libtrap creates 10 reader threads …
> Reader threads may hang on sem_wait if the semaphore is uninitialized

- pycommon/report2idea.py
- pycommon/test/doctests.py
Timestamps in EventTime, DetectTime, Ceasetime should be in interval
(CreateTime - dpast, CreateTime + dfuture).
Currently, dpast is set to 1 and dfuture is set to 0.
Additional tests (in pydoc) were written and doctests.py executes them
during `python setup.py test`.
> report2idea: validate timestamps in IDEA message before checking rules

- unirec/tests/test_time.c
- unirec/unirec.c
- unirec/ur_time.h
Previous version of ur_time_from_str() didn'ŧ parse timestamp in the RFC format including UTC timezone ('Z'). This PR add the support.
changelog: Add UTC timestamp support int ur_time_from_str().
> Unirec fixed timefromstr

- pycommon/report2idea.py
- pycommon/test/rc_23_testreporter.py
@thorgrin reported an issue about reporter modules failing when historical offline data are replayed.
This PR adds an option `-D` / `--dontvalidate` to skip check_valid_timestamps().
> report2idea: option to disable timestamp checks

- pytrap/test/unirectemplate_unittest.py
- unirec/macaddr.h
On some platforms, ether_ntoa() outputs unexpected results
(0x112233445566) instead of MAC addr notation.
This patch standardizes convertions of MAC addr UniRec type.
> unirec: macaddr: conversion from/to string using sscanf/snprintf

- libtrap/configure.ac
- libtrap/m4/ax_atomic8.m4
- libtrap/src/trap_internal.c
- libtrap/src/trap_internal.h
- unirec/macaddr.h
This PR contains configure check for atomic functions that are missing in Turris SDK toolchain. When there is no definition of `__sync_bool_compare_and_swap_8()`, libtrap defines its own.
Otherwise, gcc builtins are used.
> BUGFIX Turris SDK doesn't know 8B atomic operations

- libtrap/src/ifc_file.c
Files with just one digit suffix are not ordered correctly by default.
That means file.10 is before file.2 (alphanumeric ordering is a default
behavior).  This patch changes suffix format to 4 digits with leading
zeros, such as file.0010, file.0002.
> libtrap: file: extend suffix to 4 digits for better ordering

- libtrap/README.ifcspec.md
- libtrap/configure.ac
- libtrap/src/ifc_file.c
- libtrap/src/ifc_file.h
Improvements:
* fixed -Wformat-overflow errors
* improved names of some functions
* added one more digit into filenames (now 5 to match the maximum number of digits when using 16-bit counter)
* used 'w - write' as default mode
* disabled -Wformat-truncation warnings
* adjusted and improved documentation
* substituted some magic numbers with named constatnts
> File interface improvements

- pytrap/src/unirecmodule.c
- pytrap/test/unirectemplate_unittest.py
Pytrap UnirecTemplate.getData() now returns only memory that was set (instead of the whole allocated memory).  This saves resources when the data are sent via output IFC.
Additionally, check for argument of createMessage() was insufficient. The argument was changed to int in PyArg_ParseTupleAndKeywords() so the comparison with max size of UniRec message can work.
> Pytrap bugfixes

- libtrap/tests/test_echo_reply.c
- libtrap/tests/test_tls.sh
trap_recv() may return other codes than 'terminated' that signify failure (e.g. unsuccessful certificate verification results in 'bad params').
> libtrap - bugfix in test_echo_reply

- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tcpip_internal.h
- libtrap/src/ifc_tls.c
- libtrap/src/ifc_tls_internal.h
- libtrap/src/trap.c
- libtrap/src/trap_internal.h
- libtrap/tools/trap_stats.c
Fix unintentional busy waiting in TCP/IP and TLS interfaces resulting in high CPU usage.
Add "delay" counters to input interfaces for measuring of time intervals between receive calls (may be useful for debugging slow modules).
> libtrap: fix cpu usage

- unirec/unirec.h
* The use of statement expressions is forbidden by ANSI C but is an GCC extension.
It is used in unirec.h to define the TRAP_CTX_RECEIVE and (commented out)
UNIREC_CTX_CHECK_TEMPLATE macros. By marking these declarations as __extension__,
several build warnings are fixed.
* For further details: https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html
* This should also be supported by Clang, not tested.
> unirec: Mark usage of statement expressions as such

- libtrap/src/trap_internal.c
- libtrap/src/trap_internal.h
Test build using Turris SDK revealed some missing atomic functions.
This patch defines:
```
uint64_t __sync_add_and_fetch_8(uint64_t *ptr, uint64_t value);
uint64_t __sync_or_and_fetch_8(uint64_t *ptr, uint64_t value);
uint64_t __sync_and_and_fetch_8(uint64_t *ptr, uint64_t value);
```
when configure script detects missing atomops, e.g., for turris.
> libtrap: add missing atomic_ops for turris

- libtrap/src/trap_internal.c
The current version of code cannot be compiled on OpenWrt without atomics.
> libtrap: BUGFIX remove copy-pasted ';' from func definition

- libtrap/configure.ac
According to https://gcc.gnu.org/gcc-10/changes.html, new gcc has changed
default behavior so we get compile errors without -fno-common.
> build: gcc10+ compatibility: add -fcommon if gcc version is at least 10

- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tcpip_internal.h
- libtrap/src/trap.c
Select has limited range of file descriptors form 0-1023 https://man7.org/linux/man-pages/man2/select.2.html
>  POSIX allows an implementation to define an upper limit, advertised
via the constant FD_SETSIZE, on the range of file descriptors that
can be specified in a file descriptor set.  The Linux kernel imposes
no fixed limit, but the glibc implementation makes fd_set a fixed-
size type, with FD_SETSIZE defined as 1024, and the FD_*() macros
operating according to that limit.  To monitor file descriptors
greater than 1023, use poll(2) or epoll(7) instead.
Unfortunately, this behavior causes problems in Flowmon Networks, since file descriptors greater than 1023 are quite common.
> libtrap: replace select with poll

- README.md
Hopefully, this will save someone time as I didn't have installed
autoreconf, libtool and libxml2-dev on Ubuntu 20.04.
Let's start with some dependencies they could be extended in the future.
> README: Add dependencies

- README.md
- configure.ac
- pycommon/README
- pytrap/README
When I compiled it successfully on Ubuntu 20.04 LTS,
there was the following advise:
```
For installation of Python components run the following commands as root:
(cd pytrap; python setup.py install --record=installed-files.txt;)
(cd pycommon; python setup.py install --record=installed-files.txt;)
```
This ends up in my case that I don't have installed setuptools, but it
was trying to install for Python2. When I used python3
setup.py, it works. Let's force users to use python3.
Ubuntu provides package python-is-python2 by default.
User can choose if he wants to have this or python-is-python3.
If you don't have symlink for python, it is better to use python3.
On the other hand, Arch Linux symlinks python to python3. On Gentoo,
the choise is up user. Commonly python should be linked to …
> treewide: prefer Python3 instead of Python

- unirec/unirec.c
Fixes warning:
warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
In man pages:
```
To allow code that requires _BSD_SOURCE in glibc 2.19
and earlier and _DEFAULT_SOURCE in glibc 2.20 and
later to compile without warnings, define both _BSD_SOURCE and _DEFAULT_SOURCE.
```
> unirec.c: fix warning about deprecated _BSD_SOURCE

- libtrap/include/libtrap/trap.h
- libtrap/src/ifc_file.c
- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tls.c
- Fixed autoflush not being called when sending thread was sleeping (module was not able to send data until buffer was full)
- Fixed bug where one slow reading / idle client could block the entire module. This could happen with `WAIT`, `HALF_WAIT` or `NO_WAIT` timeouts.
Bug scenario:
```
flow source -> traffic_repeater -> flow_counter1
-> flow_counter2
```
When we stop the `flow_counter1` module and `traffic_repeater` is still running, `flow_counter2` would not be able to receive any data from `flow source`.
> libtrap bugfixes

- unirec/configure.ac
The -fcommon option was default before GCC v10.0, so adding it unconditionally is simpler. The original conditional code to add it for v10 or greater was also broken on platforms where -dumpversion reported not only the major version.
> unirec: Fix build with GCC v10.x

- libtrap/configure.ac
- libtrap/src/trap_internal.c
- libtrap/src/trap_internal.h
* Move the definition of char trap_err_msg[] from header file to
source file and declare the variable as extern in the header.
* GCC since v10.0 changes default handling of tentatively defined
global variables to be in accordance with the C standard, what
inhibits their merging by linker on multiple definition. While
it is possible to work around this behaviour by forcing -fcommon,
the better approach is to fix the definitions as is done here.
* For additional details see:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85678
> libtrap: Fix build on GCC v10.x

- pytrap/src/unirecmodule.c
- Adds method getMicroSeconds
- Adds method getMicroSecondsAsFloat
- Adds method getNanoSeconds
- Adds method getNanoSecondsAsFloat
Note: Floats are faster in python than ints.
> feat(Pytrap): Added additional time extraction methods to unirectime.

- pytrap/src/pytrapmodule.c
- pytrap/test/pytrapmodule_unittest.py
Unsupported str causes exception in the following code:
`trap.send(json.dumps(j))`
This PR should fix this issue (adding this support).
The test `pytrap/test/pytrapmodule_unittest.py` fails for the previous version.
> pytrap: support str object in TrapCtx.send()

- pytrap/setup.py
- pytrap/src/pytrap/__init__.py
- pytrap/src/pytrapmodule.c
- pytrap/src/unirecmodule.c
The new method read_nemea() works as follows:
```
Read `nrows` records from NEMEA TRAP interface given by `ifc_spec` and convert then into Pandas DataFrame.
Args:
ifc_spec (str): IFC specifier for TRAP input IFC, see https://nemea.liberouter.org/trap-ifcspec/
nrows (int): Number of records, read until end of stream (zero size message) if -1.
array (bool): Set output type to list of dictionary instead of pandas.DataFrame
Returns:
pandas.DataFrame or list of dictionary: DataFrame if array is False, otherwise, list of dictionary
Raises:
ModuleNotFoundError: When pandas is not installed.
```
The patch also adds UnirecTemplate::getDict() that converts the single
UniRec record into dict().
Example of use:
```
import pytrap
print(pytrap.read_nemea("f:~/osquery.trapcap"))
```
> pytrap: add read_nemea() returns pandas.DataFrame or list(dict)

- pycommon/reporter_config/Config.py
- pycommon/reporter_config/actions/Syslog.py
- pycommon/test/rc_17_syslog.py
- pycommon/test/rc_config/syslog-malformed-facility.yaml
- pycommon/test/rc_config/syslog-malformed-logoption.yaml
- pycommon/test/rc_config/syslog-malformed-priority.yaml
- pycommon/test/rc_config/syslog.yaml
Example config file to define new syslog custom_action is taken from
syslog.yaml test config:
```
namespace: com.example.nemea
custom_actions:
- id: mysyslog
syslog:
identifier: NEMEA
logoption: LOG_PID | LOG_CONS
facility: LOG_DAEMON
priority: LOG_ALERT
rules:
- id: 1
condition: True
actions:
- mysyslog
```
> report2idea: add `syslog` action

- pytrap/MANIFEST.in
- pytrap/docs/helpers.rst
- pytrap/docs/index.rst
- pytrap/docs/recvbulk.rst
- pytrap/nemea-pytrap.spec
- pytrap/setup.py
- pytrap/src/pytrap/__init__.py
- pytrap/src/pytrap/helpers.py
- pytrap/src/pytrapmodule.c
- pytrap/src/unirecmodule.c
- pytrap/src/unirectemplate.h
- pytrap/test/pytrapmodule_unittest.py
Added new features:
* `UnirecTemplate.getFieldsDict()` has optional argument to create dict with field ID as keys
* `UnirecTemplate.setFromDict()` fills UniRec message using a dictionary with matching keys
* `TrapCtx.sendBulk()` sends a sequence of dictionaries (that are compatible with `setFromDict()`
* new helpers.py classes were introduced: `pytrap.helpers.PytrapHelperLoad()`, `pytrap.helpers.PytrapHelperStore()`; `read_nemea()` function was moved into helpers.py
* doc was improved and new features were added; there is a new doc "module" for helpers
> pytrap: sendBulk() and other new features

- pytrap/src/unirecmodule.c
- pytrap/test/unirectemplate_unittest.py
Python string fails when non-utf8 bytes occure in the field value due to decoding error.
This patch replaces straightforward use of PyUnicode_FromStringAndSize() with
PyUnicode_DecodeUTF8(), which can be set to replace invalid bytes.
As a result, the invalid non-utf byte sequences are replaced by 0xFFFD character (dec ~ 65533).
It is worth noting that the replacement process affects performance (quite significantly).
On the other hand, valid UTF-8 strings perform similarly as before this PR.
> pytrap: apply replacement on invalid utf-8 strings implicitly

- pytrap/src/pytrapmodule.c
for loops do not allow variable defininition without -std=c99 / -std=gnu99
> pytrap: fixed compilation issue for non-C99 standard

- libtrap/ChangeLog
- libtrap/NEWS
- libtrap/configure.ac
- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tls.c
If t_rb_at() returns NULL, we cannot access its content (such as the
buffer or ref_counter).  There is currently continue after this test to
go back to the start of the loop and check is_terminated.
> libtrap: BUGFIX check return value of t_rb_at()

- pytrap/src/unirecmodule.c
- pytrap/test/unirectemplate_unittest.py
UniRec arrays were not set in UnirecTemplate.setFromDict() due to
missing check for value sequence.
New test ArrayFromDict was prepared to check this feature.
> pytrap: add capability to set arrays from dict

- libtrap/include/libtrap/trap.h
- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tcpip_internal.h
- libtrap/src/trap.c
- libtrap/src/trap_ifc.h
Recv function can obtain sequence number of the record
Function to get stats of recv interface
> Libtrap - recv function with sequence number, recv stats function

- pycommon/report2idea.py
- pycommon/reporter_config/Config.py
- pycommon/reporter_config/actions/Email.py
- Email.py: Fixed use of undefined "duration" variable if not both starttime and endtime are defined
- Config.py: Fixed printing of an exception message
- report2idea.py: improve parameter help string - specify what is the default value
- report2idea.py: print the "Starting receiving" message just once, not in the loop, which repeats every 3 seconds due to the timeout in the input interface.
> Reporters: fixes and minor improvements

- .github/workflows/c-cpp.yml
- libtrap/libtrap-varrun.conf.in
- libtrap/libtrap.spec.in
- We have changed ownership from nemead to root to maintain functionality even without nemea-supervisor
- /var/run/libtrap changed to /run/libtrap since /var/run is deprecated
- Added sticky bit permission for the tmp files directory
> Changes in tmp files

- unirec/include/unirec++/bidirectionalInterface.hpp
- unirec/include/unirec++/outputInterface.hpp
- unirec/unirec++/bidirectionalInterface.cpp
- unirec/unirec++/outputInterface.cpp
- dont send EoF if interface is not initialized
- dont set empty template
> Unirec++ - output/bidirectional interface update

- pytrap/src/unirecmodule.c
- pytrap/test/unirectemplate_unittest.py
It is a method of UnirecTemplate that internally calls ur_copy_fields() to copy values from one UniRec record to another.  It copies all fields from src object (argument), which are present in the "self".  The src argument must be of type UnirecTemplate.
> pytrap: add UnirecTemplate.copyMessage()

- pytrap/docs/conf.py
This PR enforces master_doc to index to fix doc on rockylinux8 with apparently old sphinx.
> pytrap: fixed doc config

- pytrap/src/unirecipaddr.c
Fixes incorrect behavior of `UnirecIPAddrRange.__contains__` due to incomplete type checking:
Previous behavior
```py
from pytrap import UnirecIPAddrRange, UnirecIPAddr
r = UnirecIPAddrRange("192.168.42.0/24")
a = UnirecIPAddr("192.168.42.42")
print(a in r)       # True, OK
print(str(a) in r)  # False, should TypeError
print(42 in r)      # False, should TypeError
```
New behavior
```py
from pytrap import UnirecIPAddrRange, UnirecIPAddr
r = UnirecIPAddrRange("192.168.42.0/24")
a = UnirecIPAddr("192.168.42.42")
print(a in r)       # True, OK
print(str(a) in r)  # TypeError: pytrap.UnirecIPAddrRange object expected, got 'str'.
print(42 in r)      # TypeError: pytrap.UnirecIPAddrRange object expected, got 'int'.
```
Also fixes adjacent behavior of `UnirecIPAddrRange.isOverlap` and …
> pytrap: raise type error on incorrect type

- unirec/ChangeLog
- unirec/NEWS
- unirec/configure.ac
> unirec: increased version, updated ChangeLog, released RPM package
