- python/unirec/unirec.py
(init of generated unirec template class)
> fixed wrong implementation of dynamic field unpacking

- pycommon/Makefile.am
- pycommon/ip_prefix_search.py
- pycommon/report2idea.py
- pycommon/setup.py
- pycommon/test/ip_prefix_search_unittest.py
- pytrap/test/unirectemplate_unittest.py
- pytrap/unirecmodule.c
UnirecIPAddrRange was taken from PR #22 by @plotenyondra.
Init was refactored a bit.
There are some other fixes, mainly of memory leaks.
> pytrap: partial merge of UnirecIPAddrRange

- unirec/unirec.h
> Typo in unirec error messages

- pycommon/report2idea.py
- pycommon/test/rc_10_all_actions.py
- pycommon/test/rc_14_mongo.py
- pycommon/test/rc_15_file.py
- pycommon/test/rc_16_trap.py
- pycommon/test/rc_20_multiple_actions.py
- pycommon/test/rc_21_multiple_elseactions.py
Conditional unittest skipping based on non-OS module imports
> Reporter Configuration unittest fixes

- pycommon/report2idea.py
- pycommon/reporter_config/Config.py
- pycommon/reporter_config/Parser.py
- pycommon/reporter_config/README.md
- pycommon/reporter_config/Rule.py
- pycommon/reporter_config/__main__.py
- pycommon/reporter_config/actions/Email.py
- pycommon/reporter_config/actions/File.py
- pycommon/reporter_config/actions/Trap.py
- pycommon/reporter_config/actions/Warden.py
Warden Action now takes only a reference to Warden Client instance in order to support different config for each reporter while still having a global configuration for all the other actions.
> Reporter Config: Warden Action fixture

- pycommon/reporter_config/Config.py
- pycommon/reporter_config/actions/Action.py
- pycommon/reporter_config/actions/Drop.py
- pycommon/reporter_config/actions/Email.py
- pycommon/reporter_config/actions/File.py
- pycommon/reporter_config/actions/Mark.py
- pycommon/reporter_config/actions/Mongo.py
- pycommon/reporter_config/actions/Trap.py
- pycommon/reporter_config/actions/Warden.py
- pycommon/test/rc_01_basic.py
- pycommon/test/rc_01_empty.py
- pycommon/test/rc_02_tautology.py
- pycommon/test/rc_12_mark.py
- pycommon/test/rc_22_addressgroup.py
Actions were improved, documentation (http://nemea.liberouter.org/reporting/) updated - it is still a draft but I've checked arguments of action types.
It is now possible to write advanced tests that can check what rules were performed and what actions were called.
Some `simulate` or `test` argument is now needed for actions in order to write tests of Mongo / Warden / Email. We want to check if they are called and generate a right content but we don't want to store it or send it anywhere..
Changes must be tested before releasing package.
> Pycommon actions - fixes and improvements

- unirec/configure.ac
- unirec/tests/Makefile.am
- unirec/tests/test_template_cmp.c
- unirec/unirec.c
- unirec/unirec.h
Added new function for comparison of two UniRec templates. Functions compares sets of fields in both templates (direction is not checked) and returns non-zero value (1) if templates macthes, 0 if they does not match.
> NEW FEATURE: Added function for comparison of two UniRec tempaltes.

- jenkins/Centos-Dockerfile
- jenkins/Debian-Dockerfile
- jenkins/Jenkinsfile
- pycommon/Makefile.am
There is a new internal jenkins system for automatic creation of RPM and deb packages.
The system is internal only, however, we will publish created packages in the future.
> Jenkins of liberouter

- common/Makefile.am
- common/counting_sort/counting_sort.c
- common/include/Makefile.am
- common/include/counting_sort.h
- common/tests/Makefile.am
- common/tests/counting_sort_test.c
A simple yet powerful Counting Sort which works in ascending or descending order.
> Pull request counting sort

- unirec/tests/Makefile.am
- unirec/tests/test_time.c
- unirec/unirec.c
- unirec/ur_time.h
Add function to convert string into ur_time_t (moved and revisited existing code).
Add unit test that covers ur_time_t.
> Extended UniRec API: ur_time_from_str()

- pycommon/Makefile.am
- pycommon/nemea-pycommon.spec
- pycommon/reporter_config/default.html
- pycommon/reporter_config/example.yaml
- pycommon/setup.py
Update dependencies, update example config and add default template for email action.
> Report template examples and dependencies

- common/counting_sort/counting_sort.c
- common/tests/counting_sort_test.c
- libtrap/src/ifc_tls.c
- pycommon/reporter_config/Config.py
- pycommon/reporter_config/actions/Email.py
- pycommon/reporter_config/example.yaml
Some more issues are solved by this PR:
* missing default template for Email
* invalid syntax of yaml config
There are still issues that must be solved:
* --dry (print updated configuration) (https://github.com/CESNET/Nemea-Framework/issues/89)
* check if template file(s) exists
* catch exception and print some hint when `smtp_connections` is not contained in the config while it is needed by defined email custom_action (smtp_connections is required when there is at least one email action)
> Email action updates

- libtrap/README.ifcspec.md
- libtrap/include/libtrap/trap.h
- libtrap/src/trap.c
- libtrap/src/trap_error.h
- libtrap/src/trap_ifc.h
- libtrap/src/trap_internal.h
Most changes address:
thread safety of context API functions,
data race of internal context attributes
simplification and refactoring of buffering
setting internal last error codes and messages
Requires intensive code review before merging.
Further experiments with non-blocking output interface required.
> libtrap: major changes in internal behavior

- libtrap/src/ifc_dummy.c
- libtrap/src/ifc_file.c
- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tcpip_internal.h
- libtrap/src/ifc_tls.c
- libtrap/src/ifc_tls_internal.h
- libtrap/src/trap.c
- libtrap/src/trap_ifc.h
- libtrap/tools/trap_stats.c
Libtrap statistics are extended - added info about connected clients (PID / port)
and their elapsed time during sending.
changelog: Extended statistics of service interface
> libtrap: Added client identification and sending statistics

- unirec/unirec2csv.c
- unirec/unirec2csv.h
urcsv_field() can be used to convert arbitrary field value to string.
> unirec: csv: decomposition of urcsv_record(), added urcsv_field()

- pytrap/src/unirecmodule.c
- pytrap/test/pytrapmodule_unittest.py
- pytrap/test/unirectemplate_unittest.py
- unirec/tests/test_basic.c
- unirec/unirec.c
- unirec/unirec.h
- unirec/ur_processor.sh
Added support for unirec arrays to pytrap.
> Pytrap ur array

- unirec/unirec2csv.c
Added support for unirec array types for conversion to csv.
Request code review.
> ur2csv: added support for array unirec types

- unirec/ip_prefix_search.c
- unirec/tests/test_iter.c
In an attempt to help with the current aggregator & unirecfilter situation.
> Fix some memleaks in ip_prefix_search

- libtrap/src/trap.c
> libtrap: fixed memory leak

- libtrap/README.ifcspec.md
- libtrap/src/ifc_file.c
- libtrap/src/third-party/libjansson/error.c
Memory leaks and compiler warnings fix, file mode parsing improvement and also improved module help output
> Libtrap fix

- unirec/ipaddr.h
- unirec/macaddr.h
- unirec/unirec.c
fixed compilation issues when providing const parameters to unirec functions with non-const parameters
> Ur funcs fix

- pytrap/nemea-pytrap.spec
- pytrap/setup.py
Added str in send() support
Improved doc
> pytrap: increased version, released package

- pytrap/src/pytrapmodule.c
- pytrap/src/unirecmacaddr.c
- pytrap/src/unirecmodule.c
Fixed some memory leaks idenfified using valgrind and python3 setup.py test.
> pytrap: fixed memory leaks

- unirec/tests/Makefile.am
- unirec/tests/test_resize.c
- unirec/unirec.c
This PR simulates expanding UniRec template that is addressed in #197.
> unirec: add test to extend unirec template

- pycommon/nemea-pycommon.spec
- pycommon/report2idea.py
- pycommon/reporter_config/Config.py
- pycommon/reporter_config/Parser.py
- pycommon/reporter_config/Rule.py
- pycommon/setup.py
- pycommon/test/rc_01_basic.py
- pycommon/test/rc_01_empty.py
- pycommon/test/rc_02_tautology.py
- pycommon/test/rc_11_drop.py
- pycommon/test/rc_12_mark.py
- pycommon/test/rc_14_mongo.py
- pycommon/test/rc_15_file.py
- pycommon/test/rc_17_syslog.py
- pycommon/test/rc_20_multiple_actions.py
- pycommon/test/rc_21_multiple_elseactions.py
- pycommon/test/rc_22_addressgroup.py
- pycommon/test/rc_23_testreporter.py
- pycommon/test/rc_24_testreporter_ips.py
* changed blocking to non-blocking to handle signals properly
* added new features:
- SIGUSR1 signal triggers configuration file reload
- SIGUSR2 signal makes the module to print current config including
statistics
- new feature: automatic reload of config, checks are done after N
seconds given by -a option, 0 to disable the feature - this is default
- each action of each rule has a counter stored in redis; the counter
shows how many times the action was performed
- error handling and configuration validation was improved to inform
users about issues with config file
- refactoring - some code was moved from report2idea into Config class,
Parser is no longer needed outside; there is one global Config
instance
> Report2idea improvements

- unirec/ChangeLog
- unirec/NEWS
- unirec/configure.ac
- unirec/include/unirec++/bidirectionalInterface.hpp
- unirec/include/unirec++/inputInterface.hpp
- unirec/include/unirec++/ipAddress.hpp
- unirec/include/unirec++/macAddress.hpp
- unirec/include/unirec++/outputInterface.hpp
- unirec/include/unirec++/trapModuleInfo.hpp
- unirec/include/unirec++/unirec.hpp
- unirec/include/unirec++/unirecArray.hpp
- unirec/include/unirec++/unirecException.hpp
- unirec/include/unirec++/unirecRecord.hpp
- unirec/include/unirec++/unirecRecordView.hpp
- unirec/include/unirec++/unirecTypeTraits.hpp
- unirec/include/unirec++/unirecTypes.hpp
- unirec/include/unirec++/urTime.hpp
- unirec/unirec++/Makefile.am
- unirec/unirec++/bidirectionalInterface.cpp
- unirec/unirec++/inputInterface.cpp
- unirec/unirec++/ipAddress.cpp
- unirec/unirec++/outputInterface.cpp
- unirec/unirec++/unirec.cpp
unirec++ - change namespace to Nemea
unirec++ - refactor IpAddress class
> Unirec - release new version

- unirec/include/unirec++/Makefile.am
- unirec/include/unirec++/bidirectionalInterface.hpp
- unirec/include/unirec++/inputInterface.hpp
- unirec/include/unirec++/interfaceStats.hpp
- unirec/include/unirec++/unirecRecordView.hpp
- unirec/unirec++/bidirectionalInterface.cpp
- unirec/unirec++/inputInterface.cpp
- support sequential numbers in unirec record
- support input interface stats
- fix template reload
> Unirec++ - improvments

- libtrap/src/ifc_tcpip.c
- libtrap/src/ifc_tls.c
- libtrap/src/trap_container.h
Fixes container duplication (tcpip, tls) when termination signal was received.
> Libtrap - container duplication fix
